/**
 * Auto-generated script registry
 * This file is regenerated by tools/integrate.js
 * DO NOT EDIT MANUALLY
 * 
 * Last updated: 2025-11-11T08:00:39.778Z
 */

export const scripts = [
  {
    "id": "example-script",
    "name": "📝 Example Script",
    "description": "Demonstrates framework features with a simple page highlighter",
    "version": "1.0.0",
    "enabled": true,
    "file": "example-script.user.js"
  }
];
