/**
 * Auto-generated script registry
 * This file is regenerated by tools/integrate.js
 * DO NOT EDIT MANUALLY
 * 
 * Last updated: 2025-11-11T08:31:32.894Z
 */

export const scripts = [
  {
    "id": "page-to-markdown",
    "name": "📝 Page to Markdown",
    "description": "Convert page content to Markdown with element selector",
    "version": "1.0.0",
    "enabled": true,
    "file": "page-to-markdown.user.js"
  },
  {
    "id": "dark-mode-enforcer",
    "name": "🌙 Dark Theme Enforcer",
    "description": "Apply dark glassmorphism theme to any website",
    "version": "1.0.0",
    "enabled": true,
    "file": "dark-mode-enforcer.user.js"
  }
];
