#!/usr/bin/env node

/**
 * Scan scripts/ directory and regenerate src/core/registry.js
 * This creates a manifest of all available scripts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { glob } from 'glob';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const scriptsDir = path.join(__dirname, '../scripts');
const registryPath = path.join(__dirname, '../src/core/registry.js');

async function integrate() {
  console.log('🔄 Integrating scripts into registry...\n');
  
  // Find all .user.js files
  const scriptFiles = await glob('*.user.js', { cwd: scriptsDir });
  
  if (scriptFiles.length === 0) {
    console.log('⚠️  No scripts found, creating empty registry');
    writeRegistry([]);
    return;
  }
  
  const scripts = [];
  
  for (const file of scriptFiles) {
    const filePath = path.join(scriptsDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    
    // Extract script metadata from QoL.registerScript call
    // More flexible regex to handle IIFEs and nested objects
    const registerMatch = content.match(/QoL\.registerScript\s*\(\s*\{([\s\S]*?)\n\s*\}\s*\)/m);
    if (!registerMatch) {
      console.warn(`⚠️  Skipping ${file}: No QoL.registerScript() call found`);
      continue;
    }
    
    const configStr = registerMatch[1];
    
    // Extract basic metadata
    const idMatch = configStr.match(/id\s*:\s*['"]([^'"]+)['"]/);
    const nameMatch = configStr.match(/name\s*:\s*['"]([^'"]+)['"]/);
    const descMatch = configStr.match(/description\s*:\s*['"]([^'"]+)['"]/);
    const versionMatch = configStr.match(/version\s*:\s*['"]([^'"]+)['"]/);
    const enabledMatch = configStr.match(/enabled\s*:\s*(true|false)/);
    
    if (!idMatch || !nameMatch) {
      console.warn(`⚠️  Skipping ${file}: Missing id or name`);
      continue;
    }
    
    scripts.push({
      id: idMatch[1],
      name: nameMatch[1],
      description: descMatch ? descMatch[1] : '',
      version: versionMatch ? versionMatch[1] : '1.0.0',
      enabled: enabledMatch ? enabledMatch[1] === 'true' : true,
      file
    });
    
    console.log(`✅ Registered: ${nameMatch[1]} (${idMatch[1]})`);
  }
  
  writeRegistry(scripts);
  
  console.log(`\n📦 Registry updated with ${scripts.length} script(s)\n`);
}

function writeRegistry(scripts) {
  const registryContent = `/**
 * Auto-generated script registry
 * This file is regenerated by tools/integrate.js
 * DO NOT EDIT MANUALLY
 * 
 * Last updated: ${new Date().toISOString()}
 */

export const scripts = ${JSON.stringify(scripts, null, 2)};
`;
  
  fs.writeFileSync(registryPath, registryContent);
}

integrate().catch(error => {
  console.error('❌ Integration error:', error.message);
  process.exit(1);
});
